Initial commit for calib pattern manual verify feature
lambdaloop/camibrate pull request #1
Opened 2019-12-10 15:42 UTC by JulianPitney

Proposed feature to allow users to manually go through every frame used for camera calibration and accept or reject the frame based on the accuracy of the automatic calibration pattern detection. 

**Note: Changes to <CharucoBoard> class are untested. Need to be tested before accepting changes.**

2019-12-11 20:46 UTC, lambdaloop commented on calligator/boards.py
> +        if self.manually_verify:
this should check whether pattern was found, or you get too many prompts

2019-12-11 21:03 UTC, lambdaloop requested changes
Hi @JulianPitney ,

Thank you for your contribution!!

I tested your pull request. 
The GUI generally works! I requested some changes to make it work better and to maintain code style.
Please review them and update the code as needed.

After review, it should be ready to merge.

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +                ids = None
Could you go back to the previous way to manage the ids?
That is, this code towards the end of the function:
```python
        if corners is None:
            ids = None
        else:
            ids = self.ids
```
I find it much cleaner and less error prone to update the ids based on the presence of corners at the very end.

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +        if self.manually_verify:
this should check whether pattern was found, or you get too many prompts

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +                cv2.putText(image, 'Accepted!', (int(width/4), int(height/2)), cv2.FONT_HERSHEY_SIMPLEX, 3, 255, 2, cv2.LINE_AA)
could you raise or lower the text position and make it smaller? when scanning many images quickly it can be distracting to have it be near the center

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +        if ids is not None:
When no markers are detected, ids is an empty list rather than None, so this test doesn't work

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +            if self.manually_verify:
I think the cleanest way to add the manual verify to this function is to keep everything else like it was before, and just add these lines at the bottom:
```python
if len(detectedCorners) > 0 \
     and self.manually_verify \ 
     and not self.manually_verify_board_detection(gray, detected_corners, detected_ids):
    detected_corners = detected_ids = np.float64([])
```

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +                cv2.putText(image, 'Accepted!', (int(width/4), int(height/2)), cv2.FONT_HERSHEY_SIMPLEX, 3, 255, 2, cv2.LINE_AA)
Just like for the checkerboard, could you move the text out of the middle to make it less distracting when processing many images?

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +                cv2.putText(image, 'Accepted!', (int(width/4), int(height/2)), cv2.FONT_HERSHEY_SIMPLEX, 3, 255, 2, cv2.LINE_AA)
In addition, could you have some simple instruction text in the window, in a smaller font near the corner?
Something like "Press a to accept, d to reject"

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +        # Does <findChessBoardCorners()> believe that it found the pattern?
Could you remove these comments? I appreciate the idea of commenting code, but for these statements they are redundant with the code.

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +        if self.manually_verify:
In fact, just like for the charuco board below, the cleanest way to add the code would be to add these lines at the bottom (but before the check to update the ids, see comment below):
```python
if corners is not None \
     and self.manually_verify \ 
     and not self.manually_verify_board_detection(gray, corners):
     corners = None
```

2019-12-11 21:03 UTC, lambdaloop commented on calligator/boards.py
> +    def manually_verify_board_detection(self, image, corners, pattern_was_found):
This should not even be called when pattern is not found, so the `pattern_was_found` argument is redundant.

2019-12-11 21:05 UTC, lambdaloop commented on calligator/boards.py
> +                # TODO: The docs at (https://docs.opencv.org/3.4.0/dd/d1a/group__imgproc__feature.html
Empirically, I think the function returns None if it fails, although that happens very rarely.
This is why the corners is None check happens after this in the original code, to account for this failure.

2019-12-12 19:12 UTC, JulianPitney commented
Latest commit should address all your points. Did you have a Charucko board that you were able to test the Charucko manual verification with? If not, I can put one together and do that soon.

2019-12-12 19:43 UTC, lambdaloop commented
Thank you! I will test these by tonight and let you know! 

For the previous commits, I was indeed able to test with charuco board videos and with the suggested changes it should work. If you'd like to test with some videos, here are the ones that I used:
https://drive.google.com/drive/folders/1It84D1LAX3ibZO40t-35DV5zydeGoxV2?usp=sharing

2019-12-12 20:00 UTC, JulianPitney commented
Okay cool. The fixes for calligator and anipose PRs have been pushed. Let
me know if there's anything else. All the issues you brought up were good
points. Thanks for giving me the chance to contribute haha.

On Thu, Dec 12, 2019 at 2:43 PM Pierre Karashchuk <notifications@github.com>
wrote:

> Thank you! I will test these by tonight and let you know!
>
> For the previous commits, I was indeed able to test with charuco board
> videos and with the suggested changes it should work. If you'd like to test
> with some videos, here are the ones that I used:
>
> https://drive.google.com/drive/folders/1It84D1LAX3ibZO40t-35DV5zydeGoxV2?usp=sharing
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lambdaloop/calligator/pull/1?email_source=notifications&email_token=ADTZPJL3RGFSQ2MKWGHKNX3QYKH5JA5CNFSM4JZARYSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGXZPSI#issuecomment-565155785>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADTZPJP57X4ISBVHS5V664LQYKH5JANCNFSM4JZARYSA>
> .
>

2019-12-13 03:17 UTC, lambdaloop commented
Tested the latest changes with both charuco and checkerboard. It works well, thank you!!
I will merge it now.

2019-12-13 03:17 UTC, merged